apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongoexpress-deployment
  labels:
    app: mongoexpress
#specification for deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongoexpress
  template:
    metadata:
      labels:
        app: mongoexpress
    #specification for pod
    spec:
      containers:
      - name: mongoexpress
        image: mongo-express:latest
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
        # point to the secrets
          valueFrom:
            secretKeyRef:
              name: mongodb-secrets
              key: mongo-root-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
        # point to the secrets
          valueFrom:
            secretKeyRef:
              name: mongodb-secrets
              key: mongo-root-password
        - name: ME_CONFIG_MONGODB_SERVER
        # point to the configmap
          valueFrom:
            configMapKeyRef:
              name: mongodb-configmap
              key: database_url


