apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
#specification for deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    #specification for pod
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
        # point to the secrets
          valueFrom:
            secretKeyRef:
              name: mongodb-secrets
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
        # point to the secrets
          valueFrom:
            secretKeyRef:
              name: mongodb-secrets
              key: mongo-root-password


